IMPORTATION DES PACKAGES 

In [ ]:
import numpy as np
from scipy.stats import chi2
import scipy.stats as stats
import matplotlib.pyplot as plt

GENERONS UN ECHANTILLON D'OBSERVATIONS SUIVANT UNE DISTRIBUTION GAUSSIENNE  

In [2]:
mu, sigma = 2, 0.1 # Moyenne égale à 2 et variance égale à 0.1  # dans la suite nous considérons que ces  paramètres sont inconu
                   # et que nous devons les estimer suivant l'inférence bayesienne  
n=10 # taille de l'échantion gaussien
s = np.random.normal(mu, sigma, n)
s # nos dix observations 


array([2.06094653, 1.87057334, 1.9972149 , 2.04857346, 1.98754009,
       2.1486869 , 2.24165026, 1.94891517, 2.14331911, 1.87257894])

1) Estimation de la moyenne en fixant la variance 0.1   

In [3]:
mu0, sigma0  =0, 1  # parametres de la distribution gaussienne corespondant au priore de la moyenne 

mu_post=((sigma0)*(sigma)/(sigma + n*sigma0))*( (mu0/sigma0) + (sum(s)/sigma)) # estimation de la moyenne du posterior  

sigma_post=((1/sigma0) + (n/sigma**2))**(-1) # estimation de la variance du posterior

mu_hat_dist = np.random.normal(mu_post, sigma_post, n)  
mu_hat_dist # distribution gaussienne du posteriore 

array([2.01280394, 2.01449563, 2.01189735, 2.01223019, 2.01037769,
       2.01164122, 2.01302099, 2.01138446, 2.01147165, 2.01104248])

On constate bien que les valeurs retournée ci-dessus sont proche de la vraie moyenne (2) de notre distribution initiale  

2) Estimation de la variance

In [4]:
# Ici nous générons un échantillon  suivant une distribussion chi2 en faissant la somme des carrés de n+v vaiable gaussien de moyenne 0   
# et de variance p2 qui la secode expression du Posterior hyperparameters donnée dans le tablaeu pour Scaled inverse chi-squared

v=1 # dégé de liberté de notre chi2 vaudra v+n, comme indiqué dans le tableau  
vec=[(i-mu)**2 for i in s] 
p2=((v*sigma0 + sum(vec))/(v+n))
norm = stats.norm(0,p2)

x1=np.zeros(n)
for i in range(v+n):.
    x1 = x1 + norm.rvs(size=n)**2
f=x1
f

array([0.02108697, 0.08076059, 0.03505886, 0.0801638 , 0.09889136,
       0.13173401, 0.07515498, 0.06881223, 0.0872443 , 0.04296646])

On obtient des valeurs qui sont presque toutes proches de la vraie variance
(0.1) de notre distribution initiale     